---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/kosmopay/kosmon
    - cd $DEPLOYPATH && if [ -x /opt/cpanel/composer/bin/composer ]; then /opt/cpanel/composer/bin/composer install --no-dev --optimize-autoloader --no-interaction; else composer install --no-dev --optimize-autoloader --no-interaction; fi
    - /usr/bin/php $DEPLOYPATH/artisan view:clear
    - /usr/bin/php $DEPLOYPATH/artisan cache:clear
    - /usr/bin/php $DEPLOYPATH/artisan config:clear
    - /usr/bin/php $DEPLOYPATH/artisan route:clear
